name: Check links in markdown

on: push

jobs:
  test_links_in_readme:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: List files
        run: ls -la
      - uses: docker://pandoc/core:latest
        with:
          args: >- # allows you to break string into multiple lines
            --standalone
            --from markdown
            --output=readme.html
            README.md
      - name: Run htmltest
        uses: wjdp/htmltest-action@master
        with:
          path: readme.html
